### ISSUE TITLE
Fails to parse links containing ';' characters

### ISSUE THREAD

**Issue by dlarsson** [thlorenz/parse-link-header#14]
Parsing this returns very weird results: `<http://example.org/foo;bar=1;baz=2/?q=3&r=4>; rel="self"`

**Comment by thlorenz** [comment]
Doesn't look like a valid [web link](https://tools.ietf.org/html/rfc5988) to me.
Please show me where in the spec it says to support that format.
If it is part of the spec we'll work on fixing it.

**Comment by dlarsson** [comment]
What isn't valid about it? rfc5988 references rfc3986, which mentions ';' [here](https://tools.ietf.org/html/rfc3986#section-2.2).

**Comment by thlorenz** [comment]
Yeah but not in the place you have it afaik. You have a `;` before the last `/`.
It should be after that and after a query indicator, i.e. `?`.
Here is a valid example: 
```
<https://api.github.com/user/9287/repos?page=3&per_page=100>; rel="next", ...
```
As you can see the `;` is after `?` and even after `>`. Your example has lots of `;` before those. Therefore it's not valid IMO.

**Comment by dlarsson** [comment]
I don't think there is any such restrictions. Matrix parameters (parameters to path segments) are written exactly like in my example. While matrix parameters aren't covered by any RFC, such URLs are not inherently forbidden by rfc3986.

Here's an outtake from rfc3986 on the syntax of segments (the part between / characters):

`sub-delims  = "!" / "$" / "&" / "'" / "(" / ")" / "*" / "+" / "," / ";" / "="`

`segment       = *pchar`
`segment-nz    = 1*pchar`
`segment-nz-nc = 1*( unreserved / pct-encoded / sub-delims / "@" )`
`                    ; non-zero-length segment without any colon ":"`

`pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"`

As you can see, ";" should be valid anywhere in a segment. Chapter 3 in the RFC covers these things.

The ";" in your example isn't part of the URI at all, it's part of the Link header syntax. I'm pretty sure that a ";" inside the URL, regardless of if it's before or after the last / will mess up the parser, as you're splitting the text on ";", rather than actually parsing out the URL.

**Comment by thlorenz** [comment]
OK well in that case I'll accept a PR that fixes this while maintaining the functionality for existing cases, i.e. the current tests should still pass.
I personally don't have any bandwidth to fix this. Please make sure to add a failing test for your particular example so we know it is fixed and will stay fixed in the future.
