### ISSUE TITLE
Format Link Header

### ISSUE THREAD

**Issue by jonathansamines** [thlorenz/parse-link-header#2]
Is posible to format an parsed link header back to the original format? Like url module works, with their url.parse and url.format methods?

**Comment by developit** [comment]
There is a rudimentary implementation in Express that may be of interest to you:
https://github.com/strongloop/express/blob/master/lib/response.js#L78

**Comment by thlorenz** [comment]
It may be possible, but not the function of this module.
So closing, but hopefully the provided link helps you.

**Comment by jonathansamines** [comment]
Only as a reference, i wrote my own module ([format-link-header](https://www.npmjs.com/package/format-link-header)) which format the links parsed with this module, back to the original link header string format.

**Comment by thlorenz** [comment]
Ah cool. Do you mind submitting a PR that mentions your module in the Readme with a link?
