### ISSUE TITLE
Replace `url` and `querystring` dependencies with `URL` and `URLSearchParams`

### ISSUE THREAD

**Issue by fregante** [thlorenz/parse-link-header#23]
As the title suggests, these new APIs are available globally in the recent Node releases.

**Comment by thlorenz** [comment]
Sure, but what about older releases? I'm not ready to break those for now. Thanks.

**Comment by fregante** [comment]
So it's better to use a [legacy](https://nodejs.org/api/querystring.html) API? `URL` is Node 6.13+ (way past LTS) and the `URL` global is Node 10+

**Comment by thlorenz** [comment]
Well it is until that legacy API is removed since that way we support _all_ existing apps using it.
Let's revisit when that API becomes problematic.

**Comment by fregante** [comment]
They're already problematic to users in the browsers who'd have to bundle the polyfills for these 2 modules. It'd be great to have a browser-specific local polyfill at least, which maps those two packages to thin wrappers of URL

**Comment by thlorenz** [comment]
Please file a PR with those changes.
I'll merge and bump the major version when making those changes before publishing
