### ISSUE TITLE
Publish version with `,` fix

### ISSUE THREAD

**Issue by jarofghosts** [thlorenz/parse-link-header#4]
Hey!

Sorry to bother but was wondering if there was a timeframe for when the new version might be published that includes the changes I PR'd last week.

Thanks!

**Comment by akre54** [comment]
We just ran into this bug. Version bump please?

**Comment by thlorenz** [comment]
Just publishes as 0.2.1. Thanks for the reminder.

**Comment by akre54** [comment]
Thanks
