### ISSUE TITLE
bower.json

### ISSUE THREAD

**Issue by wheresrhys** [thlorenz/parse-link-header#9]
If I put together a bare bones bower.json would you be open to adding to the repo?

A couple of reassuring things
 - bower.json needn't contain a version number (bower reads the version from the repo's git tags), so there's no overhead of maintaining that
 - Other than an initial call to add the repo to the bower registry there is no subsequent need to interact with the bower registry (unlike npm)

And one less reassuring thing
 - as xtend isn't available on bower I'd also like to either include an Object extension utility directly in this repo or use Object.assign() (supported or easily polyfillable in pretty much every js environment out there)

The reason I'd like to do all the above is to make a module I'm working on, https://github.com/wheresrhys/fetch-link, available on bower or npm. I could fork your repo or include your code directly in mine, but would much rather take the DRYer approach of consuming your module in mine.

Let me know what you think

**Comment by wheresrhys** [comment]
In all honesty, now I've written all the above out, I think the easiest route is just to copy your code and attribute to you, but let me know your thoughts

**Comment by angelxmoreno** [comment]
is @thlorenz still maintaining this? what is the link to your modified version @wheresrhys ?

**Comment by thlorenz** [comment]
Yes, but I won't add a bower.json.
bower is an anti pattern and I won't go into a discussion here why, so I want to discourage it's use, not encourage it.

**Comment by angelxmoreno** [comment]
Understood. Thank you for the reply.
